### ISSUE TITLE
[Automation]: Scripting fix / update

### ISSUE THREAD

**Issue by Jesulayomy** [Jesulayomy/SCHub#24]
Implementing a bash script or similar script, for automating installation process. This should use `configurations/configs.sh` and `configurations/server-configs.sh`.

Bonus points for interactivity if it can:

- [ ] Execute full-stack installs
    - Create venv
    - Install requirements
    - Install pre-commit hooks
    - Configure .env
    - Prompt for mysql setup
    - Generate data and dump to mysql
    - Install npm dependencies

- [ ] Execute Front-end installs
    - Set node version
    - Install npm dependencies
    - Run server

- [ ] Execute Back-end installs
    - Create venv
    - Install requirements
    - Install pre-commit hooks
    - Configure .env
    - Prompt for mysql setup
    - Run server
    - Generate data and dump to mysql

- [ ] Execute database resets
    - Reset database content using sql

Might need to address the whole thing in one PR, since the interactive script setup would need to be in place first.

**Comment by Rani1303** [comment]
Hey @Jesulayomy I would like to work on this issue.

**Comment by Jesulayomy** [comment]
Hi @Rani1303 this needs bash, you can go right ahead, I will be making an update soon for a django in an app/ directory I will push soon.

**Comment by Rani1303** [comment]
@Jesulayomy, could you please add the 'hacktoberfest-accepted' label to this issue so that it can be recognized under Hacktoberfest?

**Comment by Jesulayomy** [comment]
Sure, however Issues labels don't count.
The repository topic already includes hacktoberfest, and I can add hacktoberfest-accepted to your **Pull Request** . those are all you need for hacktoberfest to verify your contribution.

**Comment by Rani1303** [comment]
Thank you will work on this soon once you update your django app.

**Comment by Jesulayomy** [comment]
Now I have to work faster 😆

**Comment by Jesulayomy** [comment]
@Rani1303 Pushed a partial update so I can hand over to you now, working in hacktoberfest branch. You can go ahead now.

**Comment by Jesulayomy** [comment]
@Rani1303 Any updates on progress?

**Comment by Rani1303** [comment]
@Jesulayomy Hey, apologize for late reply. I am done with the script, just testing is needed. I will push the code tomorrow.

**Comment by Jesulayomy** [comment]
All good @Rani1303, Hope to see your code soon!

**Comment by Jesulayomy** [comment]
Oops I assumed it was closed when I used the Closes statement in a comment. Thanks again @Rani1303!
