### ISSUE TITLE
[Enhancement]: Adding hover and pop ups on hover to various pages like on homepage and login page.

### ISSUE THREAD

**Issue by shobhit15082003** [Jesulayomy/SCHub#27]
I want to . . .
- Implement a feature

I will do this by . . .
Simply adding some basic css/tailwind.

@Jesulayomy plz assign me this issue and mark it is hacktoberfest label.

Discord username : shobhitsrivastava

**Comment by Jesulayomy** [comment]
Seems the PR did not close this automatically @shobhit15082003 , I'll do it manually.

**Comment by Jesulayomy** [comment]
I see a mail but can't see the comment, If you feel you want another challenge you can complete let me know! I think contributions show up after some mins on hacktoberfest site. @shobhit15082003 Sorry if the notifications are a bit much.

**Comment by Jesulayomy** [comment]
That's wonderful, I do have some more plans to advance the project but being slowed down by other responsibilities irl. I remember I was talking with [LoayTarek5](https://github.com/LoayTarek5) in issue #8 about adding a popup for the pages in the student / teacher dashboards last week. But they had an issue with MySQL setup. You can preview it with the last deployment at https://schub.jesulayomi.tech  

```bash
{
  "admin": {
    "email": "tester@schub.com",
    "password": "testerpwd"
  },
  "teacher": {
    "email": "TUANN@schub.com",
    "password": "TUANNPWD"
  },
  "student": {
    "email": "GREAMEM@schub.com",
    "password": "GREAMEMPWD"
  }
}
```

**Comment by shobhit15082003** [comment]
I will look into it and if I feel like I can solve it I will ping you.
